name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: toba44/devsecops-app
  REGISTRY: docker.io
  GITOPS_REPO: git@github.com:RihabHaddad/GitOps.git

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Git short SHA
        id: vars
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Dependency Check
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        run: |
          pip install safety
          safety scan --no-link -r requirements.txt || true
          safety scan --no-link -r requirements.txt --json > safety-report.json || true

      - name: Upload safety report
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: safety-report.json

      - name: Trivy FS Scan
        id: trivy-fs
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          output: trivy-fs-report.txt

      - name: Upload Trivy FS report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-fs-report.txt

      - name: Install Snyk
        run: npm install -g snyk

      - name: Snyk Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN
          snyk test --file=requirements.txt --package-manager=pip || true
          snyk test --file=requirements.txt --package-manager=pip --json > snyk-report.json

      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${IMAGE_TAG} .

      - name: Trivy Image Scan
        run: |
          trivy image --timeout 10m \
            --scanners vuln \
            --no-progress \
            --severity HIGH,CRITICAL \
            --format table \
            --output trivy-image-report.txt \
            $IMAGE_NAME:${IMAGE_TAG} || true
          cat trivy-image-report.txt

      - name: Upload Trivy image report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image-report.txt

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${IMAGE_TAG}

      - name: Upload Safety report to Slack
        run: |
          curl -F channels="#all-graduation" \
               -F file=@safety-report.json \
               -F initial_comment="üõ°Ô∏è Safety Scan Report" \
               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
               https://slack.com/api/files.upload
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Upload Trivy FS report to Slack
        run: |
          curl -F channels="#all-graduation" \
               -F file=@trivy-fs-report.txt \
               -F initial_comment="üîç Trivy FS Scan Report" \
               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
               https://slack.com/api/files.upload
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Upload Trivy Image report to Slack
        run: |
          curl -F channels="#all-graduation" \
               -F file=@trivy-image-report.txt \
               -F initial_comment="üê≥ Trivy Image Scan Report" \
               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
               https://slack.com/api/files.upload
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Upload Snyk report to Slack
        run: |
          curl -F channels="#all-graduation" \
               -F file=@snyk-report.json \
               -F initial_comment="üîé Snyk Scan Report" \
               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
               https://slack.com/api/files.upload
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
